name: TaroEH
options:
  bundleIdPrefix: com.taro
  deploymentTarget:
    iOS: "17.0"
targets:
  TaroEH:
    type: application
    platform: iOS
    sources:
      - path: TaroEH
    resources:
      - path: TaroEH/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taro.eh
        PRODUCT_NAME: TaroEH
        MARKETING_VERSION: "1.7.18"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        INFOPLIST_FILE: TaroEH/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment
        TARGETED_DEVICE_FAMILY: "1,2"
